### ISSUE TITLE
Various issues found when using Freecoin with Faircoin

### ISSUE THREAD

**Issue by vmatekole** [Commonfare-net/social-wallet-api#18]
I am using Freecoin for the first time with Faircoin **testnet** and have the following problems:

**Call**
```curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"blockchain": "faircoin", "txid": "817e9719bc58496f8220f24a9ccffb8f8823aaeea4dbc49087ee14b1ca49610c"}' '[url]/wallet/v1/transactions/get' ```

**Response**
{"error":"Method not found"}

**Call**
```curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"blockchain": "faircoin", "address": "mtJbXVjX1CSJnoMZb6PkzunABMgMCT4mrP"}' 'http://freecoin.seedbloom.it:2000/wallet/v1/deposits/check' ```

**Response**
{"error":"No transactions for the new address found yet"}

Additionally, debug output from Freecoin:

``` 18-07-16 20:40:28 c5ec13c35990 DEBUG [social-wallet-api.handler:98] - Initialising app with name:  social-wallet-api
18-07-16 20:40:28 c5ec13c35990 DEBUG [freecoin-lib.db.freecoin:14] - Creating the freecoin mongo stores
18-07-16 20:40:28 c5ec13c35990 WARN [social-wallet-api.handler:116] - MongoDB backend connected.
18-07-16 20:40:28 c5ec13c35990 INFO [social-wallet-api.handler:128] - Faircoin config is loaded
Started server on port 3000
18-07-16 20:55:45 c5ec13c35990 DEBUG [social-wallet-api.handler:149] - Checking for transactions made to address  mtJbXVjX1CSJnoMZb6PkzunABMgMCT4mriP
18-07-16 20:56:38 c5ec13c35990 DEBUG [social-wallet-api.handler:149] - Checking for transactions made to address  mtJbXVjX1CSJnoMZb6PkzunABMgMCT4mrP
18-07-16 20:58:04 c5ec13c35990 DEBUG [social-wallet-api.handler:149] - Checking for transactions made to address  mtJbXVjX1CSJnoMZb6PkzunABMgMCT4mrP
18-07-16 21:00:13 c5ec13c35990 DEBUG [social-wallet-api.handler:149] - Checking for transactions made to address  mtJbXVjX1CSJnoMZb6PkzunABMgMCT4mrP ```


All of these results are false, can you advise on what I am doing wrong?

**Comment by aspasia** [comment]
The results are not false unless you have just made a transaction to that particular address right now. For the first problem are you sure that the URL is correct? The error message doesnt make too much sense to me, the request seems fine. What is the faircoin conf file? (send in private chat)

**Comment by aspasia** [comment]
What does "All of these results are false, can you advise on what I am doing wrong?" mean?

**Comment by aspasia** [comment]
We have created a clean install with Rama using both the wallet and fairchains. I have created a list of enhancements mostly for the readme which we will add soon. I close this issue for now, if new thing some up please let me know.
